### ISSUE TITLE
Did the signature change for UE 4.26.1?

### ISSUE THREAD

**Issue by Brunocg** [guttir14/UnrealDumper-4.25#11]
The current signature for 4.26 (x48\x8B\x05\x00\x00\x00\x00\x48\x63\x8C\x24\xE0) doesn't seem to work on UE 4.26.1. Is it supposed to stop working even for such a small change ?

**Comment by guttir14** [comment]
What game?

**Comment by Brunocg** [comment]
SCUM game.

**Comment by guttir14** [comment]
I have never touched this game before. Try to find it manually. If you can't find it yourself write me on Discord: Googloqe#4257
