### ISSUE TITLE
NamePoolData.Dump carsh 

### ISSUE THREAD

**Issue by 860000023** [guttir14/UnrealDumper-4.25#12]
I found an exception when using this tool DUMP game: OUTRIDERS Demo. But I have used RECLASS to see the structure of FNamePool. There should be no problem. I don’t know what’s wrong.
The engine of the game should be 4.25.1.

**Comment by 860000023** [comment]
outriders  FNameEntry is 
*.None..ByteProperty..IntProperty...BoolPropertyb.FloatProperty...ObjectProperty..NameProperty..DelegateProperty..DoublePropertyf.ArrayProperty...Stru


DeadByDaylight  FNameEntry is 
......None........ByteProperty........IntProperty.........BoolProperty........FloatProperty.......ObjectProperty......NameProperty..!... 



i do not kown how to fix offset by FNameEntry.Hope that can give me a little help. Thank you very much

**Comment by guttir14** [comment]
Try to apply different configs for this game, like config for RogueCompany (https://github.com/guttir14/UnrealDumper-4.25/blob/main/Dumper/engine.cpp#L62).

**Comment by 860000023** [comment]
Thank you so much, very useful.
