### ISSUE TITLE
Some classes not being dumped properly.

### ISSUE THREAD

**Issue by matty45** [guttir14/UnrealDumper-4.25#16]
I recently dumped Brickadia to find that most if not all classes to do with CoreUObject are missing.

`// Class CoreUObject.Interface
// Size: 0x28 (Inherited: 0x28)
struct UInterface : UObject {
};

// Class CoreUObject.GCObjectReferencer
// Size: 0x70 (Inherited: 0x28)
struct UGCObjectReferencer : UObject {
	char UnknownData_28[0x48]; // 0x28(0x48)
};

// Class CoreUObject.TextBuffer
// Size: 0x50 (Inherited: 0x28)
struct UTextBuffer : UObject {
	char UnknownData_28[0x28]; // 0x28(0x28)
};

// Class CoreUObject.Field
// Size: 0x30 (Inherited: 0x28)
struct UField : UObject {
	char UnknownData_28[0x8]; // 0x28(0x08)
};

// Class CoreUObject.Struct
// Size: 0xb0 (Inherited: 0x30)
struct UStruct : UField {
	char UnknownData_30[0x80]; // 0x30(0x80)
};

// Class CoreUObject.ScriptStruct
// Size: 0xc0 (Inherited: 0xb0)
struct UScriptStruct : UStruct {
	char UnknownData_B0[0x10]; // 0xb0(0x10)
};`

**Comment by guttir14** [comment]
That is normal. Engine doesn't store info about fields of CoreUObject classes. If you need to get fields of those classes, then just copy them from Unreal Engine source code.
