### ISSUE TITLE
Sdk Dump

### ISSUE THREAD

**Issue by cykagang** [guttir14/UnrealDumper-4.25#17]
Hello I am kinda new to unreal engine I wanna dump The Cycle but it uses 4.24.3 How can I add support for it

**Comment by guttir14** [comment]
If I remember correctly, UE4.24 uses UProperty instead of FProperty to store properties of structures. I have already added support for UProperty to my local version of UnrealDumper. I will push my version to repo later.

**Comment by guttir14** [comment]
UProperty support added in b5168f1ab230c470805cd94b3fceadbe4c6b122c
