### ISSUE TITLE
TFieldPath support

### ISSUE THREAD

**Issue by juniorjacob** [guttir14/UnrealDumper-4.25#19]
Hello, I was using this dumper and realized that in some games TFieldPath is a property that's not recognized by this dumper and is supported by 4.25. I am hoping this gets supported so that I can start using more of the SDK that this dumps for me.

**Comment by juniorjacob** [comment]
Other than that I would like to give immense respect to the devs who have made this project and continue to support it, this is by far the fastest, and easiest dumper I have ever seen for UE and continues to improve with time.

**Comment by guttir14** [comment]
Added in 6624c97effd4ed60a1b641d593b49d4656f31f68
