### ISSUE TITLE
I compiled and ran the software, he only created a folder with the same name as the game

### ISSUE THREAD

**Issue by 1274936135** [guttir14/UnrealDumper-4.25#21]
![FUXELM2EPNU4$OE )4O)Q7U](https://user-images.githubusercontent.com/28992655/124007523-04ceef80-da0e-11eb-9704-4a1cd0080ef9.png)

**Comment by 1274936135** [comment]
Nothing inside

**Comment by guttir14** [comment]
It's a tool, you should run it via console, so you can see its output. Output messages helps to understand what goes wrong. As I can see you started the game with anticheat
