### ISSUE TITLE
Can't init engine for this game

### ISSUE THREAD

**Issue by 1274936135** [guttir14/UnrealDumper-4.25#22]
Can't init engine for this game

![$ 9WRHM8WRO)V~41)ORWQ3O](https://user-images.githubusercontent.com/28992655/124385830-08ae8a80-dd0a-11eb-8ece-e22ff0e85b33.png)

**Comment by 1274936135** [comment]
I have turned off the protection of EAC, and EAC is not loaded

**Comment by 1274936135** [comment]
![F5I%M873IU@ 1H9X6IRD}CL](https://user-images.githubusercontent.com/28992655/124385878-43b0be00-dd0a-11eb-89fb-de72c83970ad.png)
UE4 engine version 4.13.2.0

**Comment by 1274936135** [comment]
Dead by Daylight Version ：1.9.3

**Comment by guttir14** [comment]
In order to dump old version you have to add support for it first. Dumper does support only latest versions of the game.
