### ISSUE TITLE
Not workin' for me !

### ISSUE THREAD

**Issue by ALEHACKsp** [guttir14/UnrealDumper-4.25#29]
I got a problem with that tool because when i open Fortnite nothings happen to me and no DUMPS in the folder, what could be? what do I need to do?

**Comment by Suwup** [comment]
Open the game without anti cheat, or did they just update? Because i recently updated the Fortnite decryption.

**Comment by Milxnor** [comment]
> I got a problem with that tool because when i open Fortnite nothings happen to me and no DUMPS in the folder, what could be? what do I need to do?

Open the game without anticheat and it should work, if it doesnt try to run the dumper as admin.

**Comment by ALEHACKsp** [comment]
Ok thanks boss
