### ISSUE TITLE
InterfaceProperty instead of MapProperty

### ISSUE THREAD

**Issue by doug147** [guttir14/UnrealDumper-4.25#3]
https://github.com/guttir14/UnrealDumper-4.25/blob/9ed7b1a514f49c0f4081cdb4457510596283a680/Dumper/wrappers.cpp#L435

I think this should be:

type = { PropertyType::**InterfaceProperty**, obj.GetType() };

instead of MapProperty

**Comment by guttir14** [comment]
Fixed
