### ISSUE TITLE
Im gettin' Trouble 

### ISSUE THREAD

**Issue by ALEHACKsp** [guttir14/UnrealDumper-4.25#30]
Supposed to be i got a problem with disabling anti-cheat Fortnite because ,im trying to disable BE and EAC in this case do you have any solution to help me? I tried to search how I do it and I couldn't find it anywhere ... please can you help

**Comment by Suwup** [comment]
Make a .bat file with this in it and place it in the same location as the game.
`FortniteClient-Win64-Shipping.exe -AUTH_LOGIN=unused -AUTH_PASSWORD= -AUTH_TYPE=exchangecode -epicapp=Fortnite -epicenv=Prod -EpicPortal`

**Comment by ALEHACKsp** [comment]
i did this and there's nothin' happen to me , he game anticheat is still on , i did what you asked but i was not successful with it,

BEservice is still on and I can't get as offsets, then when I go to "UNREALDUMPER" and if I run the .exe as admin it creates an epic launcher folder if I run the .exe without admin it creates the fortnite folder without nothing inside

**Comment by Suwup** [comment]
it seems like epic games launcher is being dumped instead lol, close epic games launcher and make sure that the .bat file is in `C:\Program Files\Epic Games\Fortnite\FortniteGame\Binaries\Win64`

**Comment by ALEHACKsp** [comment]
C:\Program Files\Epic Games\Fortnite\FortniteGame\Binaries\Win64
![image](https://user-images.githubusercontent.com/45023050/128925507-8a4b768c-f957-41fb-9271-61d4d4e405c9.png)
![image](https://user-images.githubusercontent.com/45023050/128925656-6206c2f6-9ad0-43c8-a610-b0297d3cff6b.png)


Well my fortnite is in HD-> "D":\Program Files\Epic Games\Fortnite\FortniteGame\Binaries\Win64 it is not on disk C, I already put the bat in the folder previously as you have asked me

**Comment by ALEHACKsp** [comment]
Not WORKIN'

**Comment by Suwup** [comment]
Is your epic games and fortnite in the same directory?

**Comment by ALEHACKsp** [comment]
No, It is in the same folder, the launcher is on disk C and Fortnite is on disk D.

**Comment by ALEHACKsp** [comment]
Ok thanks im gonna try to do that!

**Comment by ALEHACKsp** [comment]
Its workin man OMG its done 
![image](https://user-images.githubusercontent.com/45023050/129118821-cea1f383-5a8a-4405-90db-7ffc99332440.png)
I have doubt , how do I DUMP the DeadByDaylight? among other games, which uses EAC, should I do the same thing? like for example scum, rogue company, should i do the same thing?

**Comment by Milxnor** [comment]
> Its workin man OMG its done
> ![image](https://user-images.githubusercontent.com/45023050/129118821-cea1f383-5a8a-4405-90db-7ffc99332440.png)
> I have doubt , how do I DUMP the DeadByDaylight? among other games, which uses EAC, should I do the same thing? like for example scum, rogue company, should i do the same thing?

Yea?

**Comment by ALEHACKsp** [comment]
yeah ,its workin man! how can i dump the DBDLight?

**Comment by Suwup** [comment]
Some of those games you can open by just opening the executable itself, for example rogue company.

**Comment by ALEHACKsp** [comment]
Did you mean, that I can open "DEADBYDAYLIGHT" and open "UNREALDUMPER" that I will have the offsets? Will not need to do the same thing I did with "FORTNITE" , my doubt is the "Anti-cheat" will not block and blocking will not have access to the play process to DUMP it.

**Comment by ALEHACKsp** [comment]
?

**Comment by Suwup** [comment]
Just open the executable...

**Comment by ALEHACKsp** [comment]
Thanks for the Help !
