### ISSUE TITLE
Fix Fortnite String Encrytion

### ISSUE THREAD

**Issue by razfriman** [guttir14/UnrealDumper-4.25#36]
Encryption is broken.

Not sure how to update your shell code, but my algorithm for it is here: 

https://github.com/razfriman/UnrealDumper.Net/blob/master/UnrealDumper/Models/EncryptionSettings.cs#L16 with `key = 120`

**Comment by Suwup** [comment]
I already made a pull request 4 hours ago updating the Fortnite decryption for the latest if that is what you are talking about.
PR: https://github.com/guttir14/UnrealDumper-4.25/pull/33

**Comment by razfriman** [comment]
Fantastic, thanks @Suwup
