### ISSUE TITLE
Seems like its not generating static functions

### ISSUE THREAD

**Issue by Milxnor** [guttir14/UnrealDumper-4.25#39]
I'm not sure if its not generating static functions or just putting static,

**Comment by guttir14** [comment]
as i know only member function can be marked as UFunction. But you can link me an example of function that is static and added to UE4 reflection system, so i can analyze it and add appropriate update to the dumper.

**Comment by Milxnor** [comment]
> as i know only member function can be marked as UFunction. But you can link me an example of function that is static and added to UE4 reflection system, so i can analyze it and add appropriate update to the dumper.

i just took a look at knackers dumper and apparently its a function flag:
0x00002000
idk i didnt really make sure or check anything kinda just looked rq.
