### ISSUE TITLE
How to get offsets.

### ISSUE THREAD

**Issue by matty45** [guttir14/UnrealDumper-4.25#4]
Hello, am new to messing around with games which use unreal engine 4.

How do you find the needed offsets that are required to start dumping a game?

**Comment by guttir14** [comment]
Use Reclass.NET for all below.
Manually go to first object in objects array. Get offsets for UObject structure from there. 
Then dump all objects of array using this tool. Find object of class, that you need to find offsets to, in dumped objects list (Don't forget about inheritance).
Open object in Reclass.NET and find offsets.

How you find offsets:
Determine size and type of value, which we need offset to, and look for value of same size and type in game memory (E.G, defs.UObject.Outer offset represents offset to address, so you need to look for 8 bytes value with valid address). 

What game are you trying to dump classes from?

**Comment by matty45** [comment]
Brickadia, it uses 4.26 but i think the dumper might still work with it due to the engine versions not being too far apart

**Comment by matty45** [comment]
The dumper cant find the objects array which is the issue im having so far

**Comment by guttir14** [comment]
Try now

**Comment by matty45** [comment]
Thanks!, it worked!
