### ISSUE TITLE
How to add a new signature? I want to add other games

### ISSUE THREAD

**Issue by YMY1666527646** [guttir14/UnrealDumper-4.25#56]
Hi, how are you

How can I get these signatures?
I can't find these signatures with CE, x64dbg and Ida??
I want to add other games?
Is it to find the world, check his memory address and get a signature from it?
// RogueCompany | PropWitchHuntModule-Win64-Shipping | Scum
&amp;Default,
{"\x48\x8D\x0D\x00\x00\x00\x00\xE8\x00\x00\x00\x00\xC6\x05\x00\x00\x00\x00\x01\x0F\x10\x03\x4C\x8D\x44\x24\x20\x48\x8B\xC8", 30},
{"\x48\x8B\x05\x00\x00\x00\x00\x48\x8B\x0C\xC8\x48\x8D\x04\xD1\xEB", 16},
nullptr
},
// POLYGON-Win64-Shipping
&amp;Default,
{"\x48\x8D\x35\x00\x00\x00\x00\xEB\x16", 9},
{"\x48\x8d\x1d\x00\x00\x00\x00\x39\x44\x24\x68", 11},

**Comment by Suwup** [comment]
https://youtu.be/hXu2BXIMiX0
