### ISSUE TITLE
Polygon

### ISSUE THREAD

**Issue by SpencerDevv** [guttir14/UnrealDumper-4.25#81]
Found UE4 game: POLYGON-Win64-Shipping.exe
Can't enumerate modules (protected process?)

**Comment by SerseDioRe** [comment]
> Found UE4 game: POLYGON-Win64-Shipping.exe Can't enumerate modules (protected process?)

That's caused by EAC. You can just start the game without Anticheat or bypass hte ObRegisterCallback

**Comment by SpencerDevv** [comment]
How would I start the game without Anticheat?
