### ISSUE TITLE
Updating Structure offsets

### ISSUE THREAD

**Issue by ghost** [guttir14/UnrealDumper-4.25#86]
How can I find the offsets required for dumping for example the outer offset the class offset, it would be helpful to know. This source is very easy to understand and use. Thanks

**Comment by Real-Ascarre** [comment]
I found a way but not sure if it will work. Will try but if anyone comes online please do let me know how to do it.

**Comment by ghost** [comment]
I read https://github.com/guttir14/UnrealDumper-4.25/issues/4 but the problem is i am trying to dump Android Game Dead By Daylight, I already found the base addresses - FNamePool and GUObjectArray as well as GWorld by bruteforce method and they are all working perfect as i dumped Names.txt and Objects.txt, now the problem is Android games doesnt run directly on windows but through an emulator, any tips so i can view the classes properly ?

**Comment by ghost** [comment]
I found a way to do everything for android device, also made a source to generate sdk but your source helped me a lot thanks.
