### ISSUE TITLE
Dead By Daylight  Can't init engine for this game

### ISSUE THREAD

**Issue by xiaoxuan1231** [guttir14/UnrealDumper-4.25#89]
Found UE4 game: DeadByDaylight-Win64-Shipping.exe
Can't init engine for this game

D:\Desktop\SDK\UnrealDumper-4.25-main\UnrealDumper-4.25\bin\Debug\Dumper.exe (进程 32444)Exited with code 1。
What should I do

**Comment by flymoon1981** [comment]
This is because of the dumper.exe does not have permission to access the process, you can remove the protection before running!

**Comment by xiaoxuan1231** [comment]
Is there any way to remove the protection? I didn't run EAC, which is really easy to use, but several games have prompted this.

**Comment by xiaoxuan1231** [comment]
I try to use ce to read the memory normally, it is too difficult for Xiaobai

**Comment by xiaoxuan1231** [comment]
At present, I encountered this problem in version 4.27.2. I am not sure if it is a problem with version 4.27.2. At present, this is the case for 2 games, CROWZ and Dead By Daylight.

**Comment by flymoon1981** [comment]
You can remove the protection, or you can change it to DLL injection! This project supports 4.27.2, which I have tested!

**Comment by SerseDioRe** [comment]
@xiaoxuan1231 
The signature changed replace with that

  { // DeadByDaylight-Win64-Shipping
    &DeadByDaylight,
    {"\x4C\x8D\x0D\x00\x00\x00\x00\xEB\x1E\x48\x8D\x0D", 12}, 
    {"\x48\x8B\x05\x00\x00\x00\x00\x48\x8B\x0C\xC8\x48\x8D\x04\xD1\xEB", 16}, 
    nullptr
  },
  
  To run the game without AC just start it from main folder ;)

**Comment by xiaoxuan1231** [comment]
@SerseDioRe Thank you, I just saw it today, he made it
